-- Row Insert 1
select * from "playersTbl";
insert into "playersTbl"(name,active) values('Yu Ishioshin','false');

-- Row Insert 2
select * from "usersTbl";
insert into "usersTbl"(name,password,age) values('Bokuro Tan','tanbokuro123',15);

-- Table Creation
create table "hobbies"
(
    id integer not NULL generated by default as identity ( increment 1 start 1 minvalue 1 maxvalue 2147483647 cache 1 ),
    name character varying(50) not NULL,
    password character varying(50) not NULL,
    constraint "hobbies_pkey" primary key (id)
)

-- Delete Row
delete from "usersTbl" where "usersID" = 2; 


